---
- name: start apache
  hosts: ec2-18-225-209-197.us-east-2.compute.amazonaws.com
  become: true
  tasks:
    - name: httpd service started
      ansible.builtin.service:
        name: httpd
        state: started
